// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DisplayReviewController from "./display_review_controller"
application.register("display-review", DisplayReviewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import HostActionController from "./host_action_controller"
application.register("host-action", HostActionController)

import MapController from "./map_controller"
application.register("map", MapController)

import PaymentController from "./payment_controller"
application.register("payment", PaymentController)
